### ISSUE TITLE
Lookup can't be loaded - Possible bad characters

### ISSUE THREAD

**Issue by hortonew** [LukeMurphey/lookup-editor#11]
Trying to determine if this can be fixed in app, or if bad characters should be removed from csv file?  Lookup works in Splunk, but not in app. 

2017-05-17 09:56:06,262 ERROR Lookup file could not be loaded
Traceback (most recent call last):
  File "<string>", line 837, in get_lookup_contents
  File "/opt/splunk/lib/python2.7/site-packages/splunk/appserver/mrsparkle/controllers/__init__.py", line 364, in render_json
    response = json.dumps(response_data).replace("</", "<\\/")
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/opt/splunk/lib/python2.7/json/encoder.py", line 230, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/splunk/lib/python2.7/json/encoder.py", line 293, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 113: invalid start byte

**Comment by LukeMurphey** [comment]
I have a fix in the code for this. Basically, the editor fails on lookup files that contain invalid characters. Core Splunk doesn't fail on it but instead replaces the invalid characters.

I modified the lookup editor to do the same thing (ignore bad characters).

I'm planning to release this in version 2.7.0. I'll let you know once this ships.

**Comment by hortonew** [comment]
Thanks! Let me know if/when you want me to test.

**Comment by LukeMurphey** [comment]
I just pushed up a new version of the Lookup Editor with a fix for this. I released it in a maintenance release (version 2.6.2) instead of a feature release so that I could get it out faster.

You should have to bounce SplunkWeb in order for the change to take.

Let me know if this works for you.

**Comment by hortonew** [comment]
Working now - thanks for the fast turnaround!
