### ISSUE TITLE
Unable to save the lookup via REST call

### ISSUE THREAD

**Issue by MikeAnderson-E16247** [LukeMurphey/lookup-editor#73]
Am able to GET content of lookup file that I created, but unable to POST column to the file:
`curl --location --request POST 'https://lb_shc:8089/services/data/lookup_edit/lookup_contents?lookup_file=companytest.csv&namespace=search' \
--header 'Content-Type: application/octet' \
--header 'Authorization: Splunk token' \
--data-raw '"companyname,companycity"'`

I've also tried JSON data in the body, I get the following error:
`2021-05-27 12:47:43,422 ERROR Unable to save the lookup
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/lookup_editor/bin/lookup_editor_rest_handler.py", line 255, in post_lookup_contents
    request_info.session_key, request_info.user)
  File "/opt/splunk/etc/apps/lookup_editor/bin/lookup_editor/__init__.py", line 335, in update
    if not is_file_name_valid(lookup_file):
  File "/opt/splunk/etc/apps/lookup_editor/bin/lookup_editor/shortcuts.py", line 129, in is_file_name_valid
    if not allowed_path.match(lookup_file):
TypeError: expected string or bytes-like object`

Using version 3.4.6 on Splunk 8.1.3. Appreciate any help you can provide.

**Comment by MikeAnderson-E16247** [comment]
Sorry, but I was wondering if you could comment on this issue please.
Thanks
